version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2024.12@sha256:03c91d4730297b5af3718e1e81d43e210eae02be271ed7d370ccb3b994dad2bd
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REGISTRY}" -u "${DOCKER_LOGIN}" --password-stdin
          DOCKER_BUILDKIT=1 docker build \
              -t "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}" \
                .
          docker push "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}"
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker tag "${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}" "${DOCKER_REGISTRY}/${DOCKER_REPO}:latest"
              docker push "${DOCKER_REGISTRY}/${DOCKER_REPO}:latest"
          fi

workflows:
  version: 2
  lint-test-build:
    jobs:
      - build-docker-image:
          context:
            - quay-push
